/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/bluebird.glb -o src/components/BlueBird.jsx -r public -k 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useExplode } from "../hooks/useExplode";

export function BlueBird(props) {
  const { nodes, materials } = useGLTF("/models/bluebird.glb");
  const group = useRef();

  useExplode(group, { distance: 200 });

  return (
    <group {...props} dispose={null} ref={group}>
      <mesh
        name="origin"
        geometry={nodes.origin.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0, -0.387, 0]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell"
        geometry={nodes.WesternBluebird_Mesh_cell.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.073, -0.172, -0.504]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell001"
        geometry={nodes.WesternBluebird_Mesh_cell001.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.087, -0.378, 0.179]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell002"
        geometry={nodes.WesternBluebird_Mesh_cell002.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.041, -0.138, 0.22]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell003"
        geometry={nodes.WesternBluebird_Mesh_cell003.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.086, -0.356, 0.065]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell004"
        geometry={nodes.WesternBluebird_Mesh_cell004.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.135, 0.128, 0.391]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell005"
        geometry={nodes.WesternBluebird_Mesh_cell005.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.001, 0.446, 0.75]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell006"
        geometry={nodes.WesternBluebird_Mesh_cell006.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.25, 0.039, 0.061]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell007"
        geometry={nodes.WesternBluebird_Mesh_cell007.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.104, -0.232, 0.073]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell008"
        geometry={nodes.WesternBluebird_Mesh_cell008.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.095, -0.383, 0.181]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell009"
        geometry={nodes.WesternBluebird_Mesh_cell009.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.101, -0.374, 0.181]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell010"
        geometry={nodes.WesternBluebird_Mesh_cell010.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.017, 0.471, 0.684]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell011"
        geometry={nodes.WesternBluebird_Mesh_cell011.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.158, 0.282, 0.245]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell012"
        geometry={nodes.WesternBluebird_Mesh_cell012.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.093, -0.366, 0.077]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell013"
        geometry={nodes.WesternBluebird_Mesh_cell013.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.041, 0.498, 0.612]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell014"
        geometry={nodes.WesternBluebird_Mesh_cell014.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.214, -0.121, -0.24]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell015"
        geometry={nodes.WesternBluebird_Mesh_cell015.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.086, -0.374, 0.033]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell016"
        geometry={nodes.WesternBluebird_Mesh_cell016.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.092, -0.376, 0.2]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell017"
        geometry={nodes.WesternBluebird_Mesh_cell017.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.052, -0.122, -0.552]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell018"
        geometry={nodes.WesternBluebird_Mesh_cell018.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.225, 0.004, -0.055]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell019"
        geometry={nodes.WesternBluebird_Mesh_cell019.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.056, -0.375, 0.219]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell020"
        geometry={nodes.WesternBluebird_Mesh_cell020.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.056, 0.475, 0.556]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell021"
        geometry={nodes.WesternBluebird_Mesh_cell021.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.013, 0.299, 0.463]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell022"
        geometry={nodes.WesternBluebird_Mesh_cell022.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.151, 0.209, 0.037]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell023"
        geometry={nodes.WesternBluebird_Mesh_cell023.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.001, 0.603, 0.468]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell024"
        geometry={nodes.WesternBluebird_Mesh_cell024.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.134, -0.159, -0.531]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell025"
        geometry={nodes.WesternBluebird_Mesh_cell025.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.106, 0.021, 0.313]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell026"
        geometry={nodes.WesternBluebird_Mesh_cell026.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.095, -0.383, 0.258]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell027"
        geometry={nodes.WesternBluebird_Mesh_cell027.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.104, -0.277, 0.076]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell028"
        geometry={nodes.WesternBluebird_Mesh_cell028.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.09, -0.349, 0.101]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell029"
        geometry={nodes.WesternBluebird_Mesh_cell029.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.005, 0.416, 0.128]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell030"
        geometry={nodes.WesternBluebird_Mesh_cell030.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.085, -0.382, 0.019]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell031"
        geometry={nodes.WesternBluebird_Mesh_cell031.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.169, 0.158, 0.388]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell032"
        geometry={nodes.WesternBluebird_Mesh_cell032.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.24, 0.051, 0.102]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell033"
        geometry={nodes.WesternBluebird_Mesh_cell033.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.07, -0.376, 0.168]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell034"
        geometry={nodes.WesternBluebird_Mesh_cell034.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.048, 0.171, -0.135]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell035"
        geometry={nodes.WesternBluebird_Mesh_cell035.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.158, 0.177, 0.033]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell036"
        geometry={nodes.WesternBluebird_Mesh_cell036.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.026, -0.291, -0.847]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell037"
        geometry={nodes.WesternBluebird_Mesh_cell037.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.208, -0.075, -0.379]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell038"
        geometry={nodes.WesternBluebird_Mesh_cell038.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.09, -0.374, 0.077]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell039"
        geometry={nodes.WesternBluebird_Mesh_cell039.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.166, -0.027, 0.215]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell040"
        geometry={nodes.WesternBluebird_Mesh_cell040.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.131, -0.382, 0.249]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell041"
        geometry={nodes.WesternBluebird_Mesh_cell041.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.268, 0.145, 0.206]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell042"
        geometry={nodes.WesternBluebird_Mesh_cell042.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.031, -0.177, -0.072]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell043"
        geometry={nodes.WesternBluebird_Mesh_cell043.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.083, -0.368, 0.136]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell044"
        geometry={nodes.WesternBluebird_Mesh_cell044.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.155, 0.298, 0.226]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell045"
        geometry={nodes.WesternBluebird_Mesh_cell045.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.122, 0.443, 0.36]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell046"
        geometry={nodes.WesternBluebird_Mesh_cell046.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.093, -0.375, 0.231]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell047"
        geometry={nodes.WesternBluebird_Mesh_cell047.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.091, -0.365, 0.113]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell049"
        geometry={nodes.WesternBluebird_Mesh_cell049.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.016, 0.473, 0.683]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell050"
        geometry={nodes.WesternBluebird_Mesh_cell050.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.011, 0.451, 0.697]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell051"
        geometry={nodes.WesternBluebird_Mesh_cell051.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.088, -0.385, -0.01]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell052"
        geometry={nodes.WesternBluebird_Mesh_cell052.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.169, -0.154, -0.306]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell053"
        geometry={nodes.WesternBluebird_Mesh_cell053.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.138, -0.061, -0.432]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell054"
        geometry={nodes.WesternBluebird_Mesh_cell054.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.007, 0.446, 0.736]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell055"
        geometry={nodes.WesternBluebird_Mesh_cell055.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.057, -0.379, 0.218]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell056"
        geometry={nodes.WesternBluebird_Mesh_cell056.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.187, -0.101, 0.162]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell057"
        geometry={nodes.WesternBluebird_Mesh_cell057.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.092, -0.383, 0.259]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell058"
        geometry={nodes.WesternBluebird_Mesh_cell058.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.085, -0.38, 0.003]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell059"
        geometry={nodes.WesternBluebird_Mesh_cell059.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.03, -0.295, -0.848]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell060"
        geometry={nodes.WesternBluebird_Mesh_cell060.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.081, 0.03, -0.326]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell061"
        geometry={nodes.WesternBluebird_Mesh_cell061.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.008, 0.454, 0.737]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell062"
        geometry={nodes.WesternBluebird_Mesh_cell062.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.023, 0.453, 0.601]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell063"
        geometry={nodes.WesternBluebird_Mesh_cell063.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.056, -0.382, 0.225]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell064"
        geometry={nodes.WesternBluebird_Mesh_cell064.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.034, -0.238, -0.742]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell065"
        geometry={nodes.WesternBluebird_Mesh_cell065.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.093, -0.378, 0.236]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell066"
        geometry={nodes.WesternBluebird_Mesh_cell066.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.037, -0.24, -0.721]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell067"
        geometry={nodes.WesternBluebird_Mesh_cell067.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.095, -0.376, 0.152]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell068"
        geometry={nodes.WesternBluebird_Mesh_cell068.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.061, 0.533, 0.559]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell069"
        geometry={nodes.WesternBluebird_Mesh_cell069.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.093, 0.516, 0.34]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell070"
        geometry={nodes.WesternBluebird_Mesh_cell070.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.002, -0.172, -0.31]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell071"
        geometry={nodes.WesternBluebird_Mesh_cell071.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.126, -0.378, 0.222]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell072"
        geometry={nodes.WesternBluebird_Mesh_cell072.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.078, -0.227, -0.706]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell073"
        geometry={nodes.WesternBluebird_Mesh_cell073.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.013, 0.454, 0.739]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell074"
        geometry={nodes.WesternBluebird_Mesh_cell074.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.239, -0.041, -0.078]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell075"
        geometry={nodes.WesternBluebird_Mesh_cell075.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.176, -0.17, 0.019]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell076"
        geometry={nodes.WesternBluebird_Mesh_cell076.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.145, 0.085, -0.208]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell077"
        geometry={nodes.WesternBluebird_Mesh_cell077.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.073, -0.188, -0.607]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell078"
        geometry={nodes.WesternBluebird_Mesh_cell078.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.086, -0.382, 0.007]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell079"
        geometry={nodes.WesternBluebird_Mesh_cell079.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.111, -0.371, 0.178]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell080"
        geometry={nodes.WesternBluebird_Mesh_cell080.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.002, 0.46, 0.743]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell081"
        geometry={nodes.WesternBluebird_Mesh_cell081.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.086, -0.38, 0.037]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell082"
        geometry={nodes.WesternBluebird_Mesh_cell082.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.064, -0.229, 0.132]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell083"
        geometry={nodes.WesternBluebird_Mesh_cell083.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.274, 0.087, 0.261]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell084"
        geometry={nodes.WesternBluebird_Mesh_cell084.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.005, 0.452, 0.754]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell085"
        geometry={nodes.WesternBluebird_Mesh_cell085.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.104, 0.419, 0.475]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell086"
        geometry={nodes.WesternBluebird_Mesh_cell086.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.055, -0.382, 0.242]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell087"
        geometry={nodes.WesternBluebird_Mesh_cell087.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.09, -0.381, 0.005]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell088"
        geometry={nodes.WesternBluebird_Mesh_cell088.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.087, -0.381, 0.044]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell089"
        geometry={nodes.WesternBluebird_Mesh_cell089.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.076, -0.167, -0.163]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell090"
        geometry={nodes.WesternBluebird_Mesh_cell090.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.198, 0.05, 0.318]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell091"
        geometry={nodes.WesternBluebird_Mesh_cell091.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.013, -0.139, 0.06]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell092"
        geometry={nodes.WesternBluebird_Mesh_cell092.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.155, -0.187, 0.169]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell093"
        geometry={nodes.WesternBluebird_Mesh_cell093.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.084, 0.395, 0.479]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell094"
        geometry={nodes.WesternBluebird_Mesh_cell094.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.093, -0.382, 0.241]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell095"
        geometry={nodes.WesternBluebird_Mesh_cell095.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.064, -0.376, 0.18]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell096"
        geometry={nodes.WesternBluebird_Mesh_cell096.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.121, -0.381, 0.194]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell097"
        geometry={nodes.WesternBluebird_Mesh_cell097.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.064, -0.373, 0.198]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell098"
        geometry={nodes.WesternBluebird_Mesh_cell098.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.125, -0.374, 0.215]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell099"
        geometry={nodes.WesternBluebird_Mesh_cell099.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.129, -0.379, 0.231]}
      />
    </group>
  );
}

useGLTF.preload("/models/bluebird.glb");
