/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/heart.glb -o src/components/Heart.jsx -r public -k 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useExplode } from "../hooks/useExplode";
import * as THREE from "three";

export function Heart(props) {
  const { nodes, materials } = useGLTF("/models/heart.glb");
  const group = useRef();

  useExplode(group, { distance: 3, enableRotation: true });

  useEffect(() => {
    const groupWorldPosition = new THREE.Vector3();
    group.current.getWorldPosition(groupWorldPosition);

    group.current.children.forEach((mesh) => {
      mesh.originalPosition = mesh.position.clone();
      const meshWorldPosition = new THREE.Vector3();
      mesh.getWorldPosition(meshWorldPosition);

      mesh.directionVector = meshWorldPosition
        .clone()
        .sub(groupWorldPosition)
        .normalize();
      mesh.targetPosition = mesh.originalPosition
        .clone()
        .add(mesh.directionVector.clone().multiplyScalar(3));
    });
  }, []);

  const scrollData = useScroll();

  useFrame(() => {
    group.current.children.forEach((mesh) => {
      if (scrollData.offset < 0.0001) {
        if (mesh.name === "origin") {
          mesh.visible = true;
        } else {
          mesh.visible = false;
        }
      } else {
        if (mesh.name === "origin") {
          mesh.visible = false;
        } else {
          mesh.visible = true;
        }
      }
      mesh.position.x = THREE.MathUtils.lerp(
        mesh.originalPosition.x,
        mesh.targetPosition.x,
        scrollData.offset,
      );

      mesh.position.y = THREE.MathUtils.lerp(
        mesh.originalPosition.y,
        mesh.targetPosition.y,
        scrollData.offset,
      );

      mesh.position.z = THREE.MathUtils.lerp(
        mesh.originalPosition.z,
        mesh.targetPosition.z,
        scrollData.offset,
      );
    });
  });

  return (
    <group {...props} dispose={null} ref={group}>
      <mesh
        name="Heart_Full_cell"
        geometry={nodes.Heart_Full_cell.geometry}
        material={materials.Red}
        position={[-0.359, 0.12, 0.082]}
      />
      <mesh
        name="Heart_Full_cell001"
        geometry={nodes.Heart_Full_cell001.geometry}
        material={materials.Red}
        position={[0.118, -0.265, 0.195]}
      />
      <mesh
        name="Heart_Full_cell002"
        geometry={nodes.Heart_Full_cell002.geometry}
        material={materials.Red}
        position={[0.001, 0.144, -0.124]}
      />
      <mesh
        name="Heart_Full_cell003"
        geometry={nodes.Heart_Full_cell003.geometry}
        material={materials.Red}
        position={[0.332, -0.001, -0.165]}
      />
      <mesh
        name="Heart_Full_cell004"
        geometry={nodes.Heart_Full_cell004.geometry}
        material={materials.Red}
        position={[-0.397, 0.003, 0.069]}
      />
      <mesh
        name="Heart_Full_cell005"
        geometry={nodes.Heart_Full_cell005.geometry}
        material={materials.Red}
        position={[-0.042, -0.417, -0.078]}
      />
      <mesh
        name="Heart_Full_cell006"
        geometry={nodes.Heart_Full_cell006.geometry}
        material={materials.Red}
        position={[0.379, 0.094, 0.015]}
      />
      <mesh
        name="Heart_Full_cell007"
        geometry={nodes.Heart_Full_cell007.geometry}
        material={materials.Red}
        position={[-0.267, -0.16, 0.157]}
      />
      <mesh
        name="Heart_Full_cell008"
        geometry={nodes.Heart_Full_cell008.geometry}
        material={materials.Red}
        position={[-0.138, 0.095, -0.187]}
      />
      <mesh
        name="Heart_Full_cell009"
        geometry={nodes.Heart_Full_cell009.geometry}
        material={materials.Red}
        position={[0.226, -0.215, -0.101]}
      />
      <mesh
        name="Heart_Full_cell010"
        geometry={nodes.Heart_Full_cell010.geometry}
        material={materials.Red}
        position={[0.405, -0.07, 0.025]}
      />
      <mesh
        name="Heart_Full_cell011"
        geometry={nodes.Heart_Full_cell011.geometry}
        material={materials.Red}
        position={[0.017, 0.029, -0.001]}
      />
      <mesh
        name="Heart_Full_cell012"
        geometry={nodes.Heart_Full_cell012.geometry}
        material={materials.Red}
        position={[0.304, 0.172, 0.065]}
      />
      <mesh
        name="Heart_Full_cell013"
        geometry={nodes.Heart_Full_cell013.geometry}
        material={materials.Red}
        position={[-0.368, -0.09, 0.002]}
      />
      <mesh
        name="Heart_Full_cell014"
        geometry={nodes.Heart_Full_cell014.geometry}
        material={materials.Red}
        position={[0.215, -0.236, 0.129]}
      />
      <mesh
        name="Heart_Full_cell015"
        geometry={nodes.Heart_Full_cell015.geometry}
        material={materials.Red}
        position={[-0.151, -0.172, -0.149]}
      />
      <mesh
        name="Heart_Full_cell016"
        geometry={nodes.Heart_Full_cell016.geometry}
        material={materials.Red}
        position={[-0.176, -0.287, 0.005]}
      />
      <mesh
        name="Heart_Full_cell017"
        geometry={nodes.Heart_Full_cell017.geometry}
        material={materials.Red}
        position={[0.198, -0.01, -0.201]}
      />
      <mesh
        name="Heart_Full_cell018"
        geometry={nodes.Heart_Full_cell018.geometry}
        material={materials.Red}
        position={[-0.351, -0.106, -0.102]}
      />
      <mesh
        name="Heart_Full_cell019"
        geometry={nodes.Heart_Full_cell019.geometry}
        material={materials.Red}
        position={[-0.027, -0.289, -0.101]}
      />
      <mesh
        name="Heart_Full_cell020"
        geometry={nodes.Heart_Full_cell020.geometry}
        material={materials.Red}
        position={[0.321, -0.132, 0.141]}
      />
      <mesh
        name="Heart_Full_cell021"
        geometry={nodes.Heart_Full_cell021.geometry}
        material={materials.Red}
        position={[0.31, 0.168, -0.059]}
      />
      <mesh
        name="Heart_Full_cell022"
        geometry={nodes.Heart_Full_cell022.geometry}
        material={materials.Red}
        position={[-0.289, -0.196, 0.001]}
      />
      <mesh
        name="Heart_Full_cell023"
        geometry={nodes.Heart_Full_cell023.geometry}
        material={materials.Red}
        position={[0.053, -0.149, -0.144]}
      />
      <mesh
        name="Heart_Full_cell024"
        geometry={nodes.Heart_Full_cell024.geometry}
        material={materials.Red}
        position={[0.341, 0.002, 0.142]}
      />
      <mesh
        name="Heart_Full_cell025"
        geometry={nodes.Heart_Full_cell025.geometry}
        material={materials.Red}
        position={[0.295, -0.188, 0.003]}
      />
      <mesh
        name="Heart_Full_cell026"
        geometry={nodes.Heart_Full_cell026.geometry}
        material={materials.Red}
        position={[0.153, -0.278, 0.008]}
      />
      <mesh
        name="Heart_Full_cell027"
        geometry={nodes.Heart_Full_cell027.geometry}
        material={materials.Red}
        position={[0.275, 0.112, 0.159]}
      />
      <mesh
        name="Heart_Full_cell028"
        geometry={nodes.Heart_Full_cell028.geometry}
        material={materials.Red}
        position={[0.024, -0.091, 0.18]}
      />
      <mesh
        name="Heart_Full_cell029"
        geometry={nodes.Heart_Full_cell029.geometry}
        material={materials.Red}
        position={[0.113, -0.297, -0.114]}
      />
      <mesh
        name="Heart_Full_cell030"
        geometry={nodes.Heart_Full_cell030.geometry}
        material={materials.Red}
        position={[-0.137, -0.149, 0.19]}
      />
      <mesh
        name="Heart_Full_cell031"
        geometry={nodes.Heart_Full_cell031.geometry}
        material={materials.Red}
        position={[0.09, 0.201, -0.002]}
      />
      <mesh
        name="Heart_Full_cell032"
        geometry={nodes.Heart_Full_cell032.geometry}
        material={materials.Red}
        position={[-0.336, -0.109, 0.097]}
      />
      <mesh
        name="Heart_Full_cell033"
        geometry={nodes.Heart_Full_cell033.geometry}
        material={materials.Red}
        position={[0.175, 0.184, -0.115]}
      />
      <mesh
        name="Heart_Full_cell034"
        geometry={nodes.Heart_Full_cell034.geometry}
        material={materials.Red}
        position={[-0.001, -0.277, 0.185]}
      />
      <mesh
        name="Heart_Full_cell035"
        geometry={nodes.Heart_Full_cell035.geometry}
        material={materials.Red}
        position={[-0.328, -0.006, 0.154]}
      />
      <mesh
        name="Heart_Full_cell036"
        geometry={nodes.Heart_Full_cell036.geometry}
        material={materials.Red}
        position={[-0.144, -0.313, 0.179]}
      />
      <mesh
        name="Heart_Full_cell037"
        geometry={nodes.Heart_Full_cell037.geometry}
        material={materials.Red}
        position={[-0.196, 0, 0.2]}
      />
      <mesh
        name="Heart_Full_cell038"
        geometry={nodes.Heart_Full_cell038.geometry}
        material={materials.Red}
        position={[0.012, -0.012, -0.187]}
      />
      <mesh
        name="Heart_Full_cell039"
        geometry={nodes.Heart_Full_cell039.geometry}
        material={materials.Red}
        position={[-0.29, -0.123, -0.172]}
      />
      <mesh
        name="Heart_Full_cell040"
        geometry={nodes.Heart_Full_cell040.geometry}
        material={materials.Red}
        position={[0.356, 0.098, -0.108]}
      />
      <mesh
        name="Heart_Full_cell041"
        geometry={nodes.Heart_Full_cell041.geometry}
        material={materials.Red}
        position={[-0.268, 0.101, -0.169]}
      />
      <mesh
        name="Heart_Full_cell042"
        geometry={nodes.Heart_Full_cell042.geometry}
        material={materials.Red}
        position={[0.173, 0.182, 0.113]}
      />
      <mesh
        name="Heart_Full_cell043"
        geometry={nodes.Heart_Full_cell043.geometry}
        material={materials.Red}
        position={[0.135, 0.098, -0.187]}
      />
      <mesh
        name="Heart_Full_cell044"
        geometry={nodes.Heart_Full_cell044.geometry}
        material={materials.Red}
        position={[-0.215, -0.006, -0.194]}
      />
      <mesh
        name="Heart_Full_cell045"
        geometry={nodes.Heart_Full_cell045.geometry}
        material={materials.Red}
        position={[-0.171, 0.182, -0.109]}
      />
      <mesh
        name="Heart_Full_cell046"
        geometry={nodes.Heart_Full_cell046.geometry}
        material={materials.Red}
        position={[0.042, -0.411, 0.067]}
      />
      <mesh
        name="Heart_Full_cell047"
        geometry={nodes.Heart_Full_cell047.geometry}
        material={materials.Red}
        position={[0.231, -0.115, -0.164]}
      />
      <mesh
        name="Heart_Full_cell048"
        geometry={nodes.Heart_Full_cell048.geometry}
        material={materials.Red}
        position={[0.21, 0.214, -0.001]}
      />
      <mesh
        name="Heart_Full_cell049"
        geometry={nodes.Heart_Full_cell049.geometry}
        material={materials.Red}
        position={[-0.392, -0.004, -0.077]}
      />
      <mesh
        name="Heart_Full_cell050"
        geometry={nodes.Heart_Full_cell050.geometry}
        material={materials.Red}
        position={[-0.1, 0.196, 0.019]}
      />
      <mesh
        name="Heart_Full_cell051"
        geometry={nodes.Heart_Full_cell051.geometry}
        material={materials.Red}
        position={[0.149, 0.095, 0.185]}
      />
      <mesh
        name="Heart_Full_cell052"
        geometry={nodes.Heart_Full_cell052.geometry}
        material={materials.Red}
        position={[-0.222, 0.208, 0.047]}
      />
      <mesh
        name="Heart_Full_cell053"
        geometry={nodes.Heart_Full_cell053.geometry}
        material={materials.Red}
        position={[-0.236, 0.127, 0.156]}
      />
      <mesh
        name="Heart_Full_cell054"
        geometry={nodes.Heart_Full_cell054.geometry}
        material={materials.Red}
        position={[0.268, 0.113, -0.161]}
      />
      <mesh
        name="Heart_Full_cell055"
        geometry={nodes.Heart_Full_cell055.geometry}
        material={materials.Red}
        position={[-0.31, 0.171, -0.052]}
      />
      <mesh
        name="Heart_Full_cell056"
        geometry={nodes.Heart_Full_cell056.geometry}
        material={materials.Red}
        position={[0.354, -0.114, -0.112]}
      />
      <mesh
        name="Heart_Full_cell057"
        geometry={nodes.Heart_Full_cell057.geometry}
        material={materials.Red}
        position={[-0.378, 0.076, -0.117]}
      />
      <mesh
        name="Heart_Full_cell058"
        geometry={nodes.Heart_Full_cell058.geometry}
        material={materials.Red}
        position={[-0.032, 0.139, 0.141]}
      />
      <mesh
        name="Heart_Full_cell059"
        geometry={nodes.Heart_Full_cell059.geometry}
        material={materials.Red}
        position={[0.403, -0.001, -0.059]}
      />
      <mesh
        name="Heart_Full_cell060"
        geometry={nodes.Heart_Full_cell060.geometry}
        material={materials.Red}
        position={[0.199, -0.064, 0.198]}
      />
      <mesh
        name="origin"
        geometry={nodes.origin.geometry}
        material={materials.Red}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/heart.glb");
